In [1]:
import sqlite3
import pandas as pd

In [6]:
con=sqlite3.connect("../data/raw/ipl.db")
def query(sql):
    return pd.read_sql(sql,con)

In [9]:
query('SELECT COUNT(*) AS total_matches FROM matches;')

   total_matches
0           1212

In [10]:
query('''
SELECT DISTINCT season
FROM matches;
''')

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [11]:
query('''
SELECT DISTINCT match_id
FROM deliveries;
''')

      match_id
0       335982
1       335983
2       335984
3       335985
4       335986
...        ...
1207   1529282
1208   1529283
1209   1529284
1210   1529285
1211   1529286

[1212 rows x 1 columns]

In [13]:
query('''
SELECT DISTINCT bowler_type
FROM deliveries;
''')

                                       bowler_type
0                                 Right arm Medium
1                             Left arm Fast medium
2                            Right arm Fast medium
3                           Slow Left arm Orthodox
4                                  Legbreak Googly
5                            Right arm Medium fast
6                                   Right arm Fast
7                                    Left arm Fast
8                                  Left arm Medium
9                             Left arm Medium fast
10                              Right arm Offbreak
11                                        Legbreak
12                             Left arm Wrist spin
13  Right arm Medium, Right arm Offbreak, Legbreak
14                    Right arm Offbreak, Legbreak
15             Right arm Offbreak, Legbreak Googly
16            Right arm Medium, Right arm Offbreak
17     Slow Left arm Orthodox, Left arm Wrist spin
18                           Right arm Fast Medium
19
20      Right arm Offbreak, Slow Left arm Orthodox
21                                             NaN

In [20]:
query('''
SELECT match_id,season,match_winner
FROM matches
WHERE match_winner ='Mumbai Indians';
''')

     match_id season    match_winner
0     1082597   2017  Mumbai Indians
1     1082600   2017  Mumbai Indians
2     1082602   2017  Mumbai Indians
3     1082606   2017  Mumbai Indians
4     1082612   2017  Mumbai Indians
..        ...    ...             ...
150   1473487   2025  Mumbai Indians
151   1473501   2025  Mumbai Indians
152   1473509   2025  Mumbai Indians
153   1527675   2026  Mumbai Indians
154   1529273   2026  Mumbai Indians

[155 rows x 3 columns]

In [22]:
query('''
SELECT match_id,match_date,venue,match_winner
FROM matches
WHERE season ='2018';
''')

,match_id,match_date,venue,match_winner
0,1136561,2018-04-07,Wankhede Stadium,Chennai Super Kings
1,1136562,2018-04-08,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
2,1136563,2018-04-08,Eden Gardens,Kolkata Knight Riders
3,1136564,2018-04-09,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
4,1136565,2018-04-10,MA Chidambaram Stadium,Chennai Super Kings
5,1136566,2018-04-11,Sawai Mansingh Stadium,Rajasthan Royals
6,1136567,2018-04-12,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
7,1136568,2018-04-13,M.Chinnaswamy Stadium,Royal Challengers Bangalore
8,1136569,2018-04-14,Wankhede Stadium,Delhi Capitals
9,1136570,2018-04-14,Eden Gardens,Sunrisers Hyderabad
10,1136571,2018-04-15,M.Chinnaswamy Stadium,Rajasthan Royals
11,1136572,2018-04-15,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
12,1136573,2018-04-16,Eden Gardens,Kolkata Knight Riders
13,1136574,2018-04-17,Wankhede Stadium,Mumbai Indians
14,1136575,2018-04-18,Sawai Mansingh Stadium,Kolkata Knight Riders
15,1136576,2018-04-19,Punjab Cricket Association IS Bindra Stadium,Punjab Kings
16,1136577,2018-04-20,Maharashtra Cricket Association Stadium,Chennai Super Kings
17,1136578,2018-04-21,Eden Gardens,Punjab Kings
18,1136579,2018-04-21,M.Chinnaswamy Stadium,Royal Challengers Bangalore
19,1136580,2018-04-22,Rajiv Gandhi International Stadium,Chennai Super Kings
20,1136581,2018-04-22,Sawai Mansingh Stadium,Rajasthan Royals
21,1136582,2018-04-23,Arun Jaitley Stadium,Punjab Kings
22,1136583,2018-04-24,Wankhede Stadium,Sunrisers Hyderabad
23,1136584,2018-04-25,M.Chinnaswamy Stadium,Chennai Super Kings
24,1136585,2018-04-26,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
25,1136586,2018-04-27,Arun Jaitley Stadium,Delhi Capitals
26,1136587,2018-04-28,Maharashtra Cricket Association Stadium,Mumbai Indians
27,1136588,2018-04-29,Sawai Mansingh Stadium,Sunrisers Hyderabad
28,1136589,2018-04-29,M.Chinnaswamy Stadium,Kolkata Knight Riders
29,1136590,2018-04-30,Maharashtra Cricket Association Stadium,Chennai Super Kings
30,1136591,2018-05-01,M.Chinnaswamy Stadium,Royal Challengers Bangalore
31,1136592,2018-05-02,Arun Jaitley Stadium,Delhi Capitals
32,1136593,2018-05-03,Eden Gardens,Kolkata Knight Riders
33,1136594,2018-05-04,Holkar Cricket Stadium,Mumbai Indians
34,1136595,2018-05-05,Maharashtra Cricket Association Stadium,Chennai Super Kings
35,1136596,2018-05-05,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
36,1136597,2018-05-06,Wankhede Stadium,Mumbai Indians
37,1136598,2018-05-06,Holkar Cricket Stadium,Punjab Kings
38,1136599,2018-05-07,Rajiv Gandhi International Stadium,Sunrisers Hyderabad
39,1136600,2018-05-08,Sawai Mansingh Stadium,Rajasthan Royals
40,1136601,2018-05-09,Eden Gardens,Mumbai Indians
41,1136602,2018-05-10,Arun Jaitley Stadium,Sunrisers Hyderabad
42,1136603,2018-05-11,Sawai Mansingh Stadium,Rajasthan Royals
43,1136604,2018-05-12,Holkar Cricket Stadium,Kolkata Knight Riders
44,1136605,2018-05-12,Arun Jaitley Stadium,Royal Challengers Bangalore
45,1136606,2018-05-13,Maharashtra Cricket Association Stadium,Chennai Super Kings
46,1136607,2018-05-13,Wankhede Stadium,Rajasthan Royals
47,1136608,2018-05-14,Holkar Cricket Stadium,Royal Challengers Bangalore
48,1136609,2018-05-15,Eden Gardens,Kolkata Knight Riders
49,1136610,2018-05-16,Wankhede Stadium,Mumbai Indians
50,1136611,2018-05-17,M.Chinnaswamy Stadium,Royal Challengers Bangalore
51,1136612,2018-05-18,Arun Jaitley Stadium,Delhi Capitals
52,1136613,2018-05-19,Sawai Mansingh Stadium,Rajasthan Royals
53,1136614,2018-05-19,Rajiv Gandhi International Stadium,Kolkata Knight Riders
54,1136615,2018-05-20,Arun Jaitley Stadium,Delhi Capitals
55,1136616,2018-05-20,Maharashtra Cricket Association Stadium,Chennai Super Kings
56,1136617,2018-05-22,Wankhede Stadium,Chennai Super Kings
57,1136618,2018-05-23,Eden Gardens,Kolkata Knight Riders
58,1136619,2018-05-25,Eden Gardens,Sunrisers Hyderabad
59,1136620,2018-05-27,Wankhede Stadium,Chennai Super Kings

In [26]:
query('''
SELECT match_id,season,venue,city
FROM matches
WHERE city ='Mumbai';
''')

     match_id season                     venue    city
0     1082597   2017          Wankhede Stadium  Mumbai
1     1082600   2017          Wankhede Stadium  Mumbai
2     1082606   2017          Wankhede Stadium  Mumbai
3     1082614   2017          Wankhede Stadium  Mumbai
4     1082618   2017          Wankhede Stadium  Mumbai
..        ...    ...                       ...     ...
180   1527675   2026  Wankhede Stadium, Mumbai  Mumbai
181   1527693   2026  Wankhede Stadium, Mumbai  Mumbai
182   1529267   2026  Wankhede Stadium, Mumbai  Mumbai
183   1529276   2026  Wankhede Stadium, Mumbai  Mumbai
184   1529284   2026  Wankhede Stadium, Mumbai  Mumbai

[185 rows x 4 columns]

In [32]:
query('''
SELECT match_id,season,venue,match_winner,win_by_runs
FROM matches
WHERE win_by_runs>=150;
''')

Empty DataFrame
Columns: [match_id, season, venue, match_winner, win_by_runs]
Index: []

In [33]:
query('''
SELECT match_id,season,venue,team1,team2
FROM matches
WHERE match_winner IS NULL;
''')

Empty DataFrame
Columns: [match_id, season, venue, team1, team2]
Index: []

In [37]:
query('''
SELECT match_id,venue,match_winner
FROM matches
ORDER BY match_date DESC
LIMIT 10;
''')

,match_id,venue,match_winner
0,1529286,"Sawai Mansingh Stadium, Jaipur",Delhi Capitals
1,1529285,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans
2,1529284,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad
3,1529283,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals
4,1529282,"Arun Jaitley Stadium, Delhi",Royal Challengers Bangalore
5,1529280,"MA Chidambaram Stadium, Chepauk, Chennai",Gujarat Titans
6,1529281,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants
7,1529278,"Arun Jaitley Stadium, Delhi",Punjab Kings
8,1529279,"Sawai Mansingh Stadium, Jaipur",Sunrisers Hyderabad
9,1529277,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bangalore

In [38]:
query('''
SELECT DISTINCT d.batter
FROM deliveries AS d 
LEFT JOIN players p
ON p.player_name =d.batter
WHERE player_name IS NULL
''')

Empty DataFrame
Columns: [batter]
Index: []