In [1]:
import pandas as pd
import sqlite3
con = sqlite3.connect("C:/Users/fathi/Downloads/ipl sem 3/IPL-Cricket-Analyticss/data/raw/ipl.db")
def q(sql):
    return pd.read_sql(sql,con)

QUESTION 18

In [13]:
q("""
SELECT *
FROM matches
WHERE win_by_runs IS NULL;
""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,None,7.0,win,SPD Smith,4,3,4,4,36.0
1,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,None,10.0,win,CA Lynn,5,6,6,6,57.0
2,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,None,6.0,win,GJ Maxwell,494,4,494,494,71.0
3,1082596,2017,6,Hyderabad,2017-04-09,Indian Premier League,6.0,male,T20,T20,...,Sunrisers Hyderabad,None,9.0,win,Rashid Khan,2,5,2,2,22.0
4,1082597,2017,6,Mumbai,2017-04-09,Indian Premier League,7.0,male,T20,T20,...,Mumbai Indians,None,4.0,win,N Rana,3,6,3,3,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,None,9.0,win,JR Hazlewood,252,1,1,1,4664.0
662,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,None,6.0,win,D Ferreira,494,134,134,134,11389.0
663,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,None,6.0,win,H Klaasen,3,2,3,2,1740.0
664,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,None,4.0,win,JO Holder,1,615,615,615,4098.0
665,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,None,7.0,win,KL Rahul,134,252,134,252,1409.0

In [24]:
q("""
SELECT match_winner ,COUNT(*) AS total_no_of_matches
FROM matches
GROUP BY match_winner
ORDER BY match_winner DESC;""" )

                   match_winner  total_no_of_matches
0           Sunrisers Hyderabad                  132
1   Royal Challengers Bangalore                  139
2        Rising Pune Supergiant                   15
3              Rajasthan Royals                  125
4                  Punjab Kings                  130
5                 Pune Warriors                   13
6                Mumbai Indians                  155
7          Lucknow Super Giants                   33
8         Kolkata Knight Riders                  137
9          Kochi Tuskers Kerala                    6
10               Gujarat Titans                   42
11                Gujarat Lions                   13
12               Delhi Capitals                  126
13          Chennai Super Kings                  146

In [16]:
q("""
SELECT venue
FROM venues

EXCEPT

SELECT venue
FROM matches;
""")

Empty DataFrame
Columns: [venue]
Index: []

In [22]:
q("""
SELECT COALESCE(city, 'UNKNOWN') AS city
FROM matches;
""")

                city
0          Bangalore
1          Hyderabad
2               Pune
3             Rajkot
4             Indore
...              ...
1207           Delhi
1208  New Chandigarh
1209          Mumbai
1210       Ahmedabad
1211          Jaipur

[1212 rows x 1 columns]