In [2]:
import pandas as pd 
import sqlite3
con=sqlite3.connect('../data/raw/ipl.db')
def q(sql):
    return pd.read_sql(sql,con)

QUESTION NO 5

In [3]:
q("""
  SELECT  player_name,field_pos 
  FROM players
  LIMIT 10;""")

     player_name field_pos
0     MN Samuels
1      SB Jakati
2      DA Warner
3    RA Tripathi
4       S Nadeem
5      MK Pandey
6  KS Williamson
7      G Gambhir
8      MK Tiwary
9        M Vohra

In [4]:
q("""
  SELECT field_pos
  FROM players
  LIMIT 10;""")

  field_pos
0
1
2
3
4
5
6
7
8
9

In [5]:
q("""
  SELECT COUNT(*) AS total_deliveries
  FROM deliveries;""")

   total_deliveries
0            288226

HERE WE USED SELECT and COUNT(*) TO GET THE TOTAL BOWLS.THIS QUERY DESCRIBES THE TOTAL BALLS BOWLED OVER THE PLAYERS IN  TEAMS

In [8]:
q("""
  SELECT match_id,win_by_runs
  FROM matches
  ORDER BY win_by_runs DESC 
  LIMIT 5;""")

   match_id  win_by_runs
0   1082635        146.0
1    980987        144.0
2    335982        140.0
3    829785        138.0
4    598027        130.0

HERE WE USED DESC IT SHOWS THE HIGHEST RUN VICTORIES ACROSS MATCHES

In [7]:
q("""
  SELECT match_winner, COUNT(*) AS match_won
  FROM matches
  GROUP BY match_winner
  ORDER BY match_won DESC;
  """)

                   match_winner  match_won
0                Mumbai Indians        155
1           Chennai Super Kings        146
2   Royal Challengers Bangalore        139
3         Kolkata Knight Riders        137
4           Sunrisers Hyderabad        132
5                  Punjab Kings        130
6                Delhi Capitals        126
7              Rajasthan Royals        125
8                Gujarat Titans         42
9          Lucknow Super Giants         33
10       Rising Pune Supergiant         15
11                Pune Warriors         13
12                Gujarat Lions         13
13         Kochi Tuskers Kerala          6